### ISSUE TITLE
Provide 'old' configurator to support older hardware/builds

### ISSUE THREAD

**Issue by mungewell** [paradajz/OpenDeck#16]
As hinted in issue #15, the configurator no longer supports older builds of OpenDeck.

It's great that the feature set of the project is moving on and I think you are really awesome for doing and 'donating' the project to the masses via GitHub.

Unfortunately the masses are not always as keen/able to update the firmware on their units. This is especially true when all you need to do is tweak a setting before a gig, but then find out things have changed since you last configured.... :-O

Can I suggest that the 'new' configurator provides links to older copies of itself to support older hardware/builds? I guess this could just be a link to an old copy in a subdirectory.

Perhaps the configurator could use the version number returned from the hardware and make the selection automatically.

**Comment by paradajz** [comment]
> As hinted in issue #15, the configurator no longer supports older builds of OpenDeck.

Well, it doesn't support only the General tab, the rest of the configurator works.

This is something I really don't like in the configurator but as I've mentioned on few places the UI was developed by someone else. I am unable to change and tweak the underlying logic behind it since 1) I am not a Web developer and 2) even if I was, the core UI code was run through obfuscator and the original source code is lost. As a result, core code is a mess. As soon as I add something new to the OpenDeck/UI, the UI either crashes or just blanks the entire screen for a tab in which settings have been added (unless the firmware on the board is on latest version) which annoys my users as much as it annoys me. 

> Perhaps the configurator could use the version number returned from the hardware and make the selection automatically.

That was my idea as well, but I don't know how to do it. Ideally, parameters which can't be retrieved just wouldn't be loaded instead of crapping out the entire screen.

**Comment by paradajz** [comment]
I will try to build offline version of the configurator using Electron or something similar and bundle it with each release. This should somewhat resolve this.

**Comment by paradajz** [comment]
Info on how to access older versions of UI is now mentioned in [README](https://github.com/paradajz/OpenDeck/blob/master/README.md#web-ui). Also, each release now contains link to fixed version of the tool:

https://github.com/paradajz/OpenDeck/releases
